/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RegisterMusicDirectorMicroService;

import org.junit.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
     
    }
}
