/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MusicDirectorsList;

import org.junit.Test;

//import com.list.MusicDirectors.MusicDirectorsApplication;

//import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        //MusicDirectorsApplication classUnderTest = new MusicDirectorsApplication();
       // assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}